export const selectors = {
  ingredientItem: '[data-testid="ingredient-item"]',
  ingredientMain: '[data-cy="main"]',
  ingredientBun: '[data-cy="bun"]',
  ingredientSauce: '[data-cy="sauce"]',
  modal: '[data-cy="modal"]',
  modalOverlay: '[data-cy="modal-overlay"]',
  modalClose: '[data-cy="modal-close"]',
  buttonOrder: '[data-testid="order-button"]',
  burgerConstructor: '[data-cy="burger-constructor"]',
  ingredientNumber: '[data-testid="order-number"]',
  ingredientBunTop: '[data-cy="constructor-bun-top"]',
  ingredientBunBottom: '[data-cy="constructor-bun-bottom"]',
  modalTitle: '[data-cy="modal-title"]',
  modalCalories: '[data-cy="modal-calories"]',
  modalProteins: '[data-cy="modal-proteins"]',
  modalFat: '[data-cy="modal-fat"]',
  modalCarbohydrates: '[data-cy="modal-carbohydrates"]'
};
